version: '3.9'


x-environment: &environment
  DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-}
  DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-}
  DJANGO_LANGUAGE_CODE: ${DJANGO_LANGUAGE_CODE:-}
  DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE:-}
  DJANGO_COLLECT_STATIC: ${DJANGO_COLLECT_STATIC:-}
  DJANGO_REST_AUTH_TOKEN_TTL: ${DJANGO_REST_AUTH_TOKEN_TTL:-}
  DJANGO_REST_EXPOSE_AUTH_API: ${DJANGO_REST_EXPOSE_AUTH_API:-}
  DJANGO_BASE_PATH: ${DJANGO_BASE_PATH:-}
  AUTH_DB_URL: ${AUTH_DB_URL:-}
  REDIS_URL: redis://redis:6379
  DATABASE_URL: ${DATABASE_URL:-}


services:
  redis:
    image: redis:alpine
  django:
    image: harleyking/grigory:${TAG:-latest}
    environment: *environment
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
  celery:
    image: harleyking/grigory:${TAG:-latest}
    command: celery -A core worker -l debug --concurrency 1 -P solo -E
    entrypoint: []
    environment: *environment
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  celery-beat:
    image: harleyking/grigory:${TAG:-latest}
    command: celery -A core beat -l debug
    entrypoint: []
    environment: *environment
