services:
  postgres:
    image: postgres:12
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_DB=grigory
      - POSTGRES_USER=grigory
      - POSTGRES_PASSWORD=grigory
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  django:
    command: gunicorn --workers 1 --threads 1 --reload
    build:
      context: .
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgres://grigory:grigory@postgres:5432/grigory
    ports:
      - "${DJANGO_WEB_PORT:-}:8000"
    volumes:
      - .:/home/django
  celery:
    command: celery -A core worker -l debug --concurrency 1 -P solo -E
    depends_on:
      - django
    environment:
      - DATABASE_URL=postgres://grigory:grigory@postgres:5432/grigory
    volumes:
      - .:/home/django
  celery-beat:
    command: celery -A core beat -l debug
    depends_on:
      - django
    environment:
      - DATABASE_URL=postgres://grigory:grigory@postgres:5432/grigory
    volumes:
      - .:/home/django


volumes:
  postgres_data:
