FROM python:3.10-slim-bullseye as oracle

RUN apt-get update && \
    apt-get install -y wget unzip --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://download.oracle.com/otn_software/linux/instantclient/219000/instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip && \
    unzip instantclient-basiclite-linux.x64-21.9.0.0.0dbru.zip -d /opt/


FROM python:3.10-slim-bullseye as base

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y --no-install-recommends libaio1 curl && \
    rm -rf /var/lib/apt/lists/*


FROM base as builder

COPY requirements.txt .

RUN python -m venv /venv && \
    source /venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir cx_Oracle==8.3.0


FROM base

WORKDIR /home/django

COPY --from=builder /venv /venv

COPY --from=oracle /opt/instantclient_21_9 /opt/instantclient_21_9

ENV PATH="/venv/bin:$PATH"

ENV PYTHONUNBUFFERED 1

ENV LD_LIBRARY_PATH=/opt/instantclient_21_9

COPY . .

RUN chmod +x /home/django/entrypoint.sh

ENTRYPOINT ["/home/django/entrypoint.sh"]

CMD ["gunicorn"]

EXPOSE 8000
