site_name: Grigory
site_description: 'Grigory is just another messaging service.'
site_author: 'Rustam Astafeev'
docs_dir: docs/
repo_name: 'Anttek-io/grigory'
repo_url: 'https://github.com/Anttek-io/grigory'
nav:
  - Home: index.md
  - Quickstart with no Docker: docs/quickstart_no_docker.md
theme:
  name: 'material'