site_name: Grigory
site_description: 'Grigory is just another messaging service.'
site_author: 'Rustam Astafeev'
docs_dir: docs/
repo_name: 'Anttek-io/grigory'
repo_url: 'https://github.com/Anttek-io/grigory'
nav:
  - Home: index.md
  - Demo: demo.md
  - Requirements: requirements.md
  - Quickstart: quickstart.md
  - Docker images: docker-images.md
  - Postman workspace: postman-workspace.md
theme:
  name: 'material'