# Generated by Django 4.1 on 2023-04-05 12:14

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], default='private', max_length=7)),
                ('slug', models.SlugField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('users', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ('-id', 'slug', 'chat_type'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('text', models.TextField()),
                ('who_read', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('-timestamp',),
            },
        ),
    ]
