# Generated by Django 3.2 on 2023-05-04 05:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_users_chat_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='who_seen',
        ),
        migrations.AddField(
            model_name='chat',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='created_chats', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=32, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(32), django.core.validators.RegexValidator('^[a-zA-Z_]{3,32}$', 'Enter a valid slug.')]),
        ),
        migrations.CreateModel(
            name='MessageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='views', to='app.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='message_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message View',
                'verbose_name_plural': 'Message Views',
                'ordering': ('-timestamp',),
                'unique_together': {('message', 'user')},
            },
        ),
    ]
