# Generated by Django 3.2 on 2023-05-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chat_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
    ]
