# Generated by Django 3.2 on 2023-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_attachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ready',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
