# Generated by Django 4.1 on 2023-04-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('user_id', models.PositiveBigIntegerField(db_index=True, verbose_name='User')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_use', models.DateTimeField(auto_now=True, verbose_name='Last use')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
