name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract release tag
      id: extract_tag
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          const tag = context.ref.replace('refs/tags/', '')
          return tag
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the main Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}
    - name: Build the oracle Docker image
      run: |
        docker build . -f Dockerfile-oracle -t ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}-oracle
    - name: Tag the main Docker image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}} ${{ secrets.DOCKER_USERNAME }}/grigory:latest
    - name: Tag the oracle Docker image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}-oracle ${{ secrets.DOCKER_USERNAME }}/grigory:latest-oracle
    - name: Push the main Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:latest
    - name: Push the oracle Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}-oracle
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:latest-oracle
