name: Publish Docker images

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract release tag
      id: extract_tag
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          const tag = context.ref.replace('refs/tags/', '')
          return tag
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image
      run: |
        DOCKER_BUILDKIT=1 docker build . -t ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}
    - name: Tag image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}} ${{ secrets.DOCKER_USERNAME }}/grigory:latest
    - name: Push image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:${{steps.extract_tag.outputs.result}}
        docker push ${{ secrets.DOCKER_USERNAME }}/grigory:latest
